version: "3"

services:
  shopping-app-django-postgres-db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DJANGO_DATABASE_USER}
      POSTGRES_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      POSTGRES_DB: ${DJANGO_DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DJANGO_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres-django-network
    restart: always

  shopping-app-django-postgres-db-dev:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DEV_DJANGO_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEV_DJANGO_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEV_DJANGO_DATABASE_NAME}
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DEV_DJANGO_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      shopping-app-django-postgres-db:
        condition: service_healthy
    networks:
      - postgres-django-network
    restart: always

  shopping-django-app:
    build: ./backend
    environment:
      DJANGO_DATABASE_USER: ${DJANGO_DATABASE_USER}
      DJANGO_DATABASE_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      DJANGO_DATABASE_NAME: ${DJANGO_DATABASE_NAME}
      DJANGO_KEY: ${DJANGO_KEY}
    command:
      python -m uvicorn shoppingapp.configs.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      shopping-app-django-postgres-db:
        condition: service_healthy
    networks:
      - postgres-django-network
    restart: always

  shopping-django-server:
    build: .
    environment:
      DJANGO_KEY: ${DJANGO_KEY}
    command:
      ./bin/caddy run Caddyfile
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      shopping-django-app:
        condition: service_started
    networks:
      - postgres-django-network
    restart: always

  shopping-app-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - postgres-django-network
    restart: always

networks:
  postgres-django-network:
    driver: bridge

volumes:
  postgres-data:
    external: false
  dev-postgres-data:
    external: false
