name: Checks

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read

jobs:
  Backend-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup
        working-directory: ./backend
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Lint and Docs Styling
        working-directory: ./backend
        run: |
          pipenv run black . --check
          pipenv run flake8 . --max-line-length=100
          pipenv run pydocstyle .
      - name: Docker build
        working-directory: ./backend
        run: |
          docker build -t backend:latest .

  Frontend-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16"
      - name: Setup
        working-directory: ./frontend
        run: |
          npm ci
      - name: Lint and Docs Styling
        working-directory: ./frontend
        run: |
          npm run lint
      - name: Build
        working-directory: ./frontend
        run: |
          npm run build

  Server-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        working-directory: ./server
        run: |
          docker build -t server:latest .
